config/routes.rb
MyWebsite::Application.routes.draw do
  root 'pages#index'
  resources :pages
  get 'about', :to => 'pages#about'
  
  

end

app/models/page.rb
class Page < ActiveRecord::Base
	validates :name, :presence => true, :length => {:maximun => 50, :minimum => 3}
	validates :message, :presence => true, :length => {:maximun => 140, :minimum => 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end

	def new
		@page = Page.new
	end

	def create
		@page = Page.create(page_params)
		if @page.invalid?
			flash[:error] = '<strong>Could not save</strong>, the data you entered is incorrect.'
		end	
		redirect_to about_path
	end

	def about
		@page = Page.last
		#@page = Page.all.order('id DESC')
	end

	private

	def page_params
		params.require(:page).permit(:name, :message)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Strategizer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<nav class="navbar navbar-transparent navbar-relative" role="navigation">
		  <div class="navbar-inner"> 
			  	<div class="container-fluid">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      	<a href="http://jteklu-mywebsite.herokuapp.com/" class="navbar-brand">
                    	<img src="http://ec2-54-69-36-221.us-west-2.compute.amazonaws.com/wp-content/uploads/2014/12/logo-grey1.png"/>
                	</a>
			    </div>

			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <ul class="nav navbar-nav navbar-right">
			      	<li><%= link_to "HOME", root_path %></li>
			        <li><%= link_to "ABOUT", about_path %></li>
			        <li><%= link_to "MESSAGE", new_page_path, :data => {:toggle => 'modal', :target => '#myModal'} %></li>	
			      </ul>
			    </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
		 </div>
		</nav>
</header>

	<div class="jumbotron">
		<div class="container">

<%= yield %>

		</div>
 	</div>

	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
			    <div class="modal-header">
			       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			       <h4 class="modal-title" id="myModalLabel">Leave Your Message</h4>
			    </div>
			    	<%= simple_form_for Page.new do |f| %>
				<div class="modal-body">
					<%= f.input :name, :label => "Your name", :placeholder => "John Snow." %>
					<br />
					<%= f.input :message, :lable => "Your comment", :placeholder => "Brothers, winter is coming!" %>
			    </div>
			    <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			        <%= f.submit 'Submit', :class => 'btn btn-danger' %>
			    </div>
			    	<% end %>
			</div>
		</div>
	</div>
	
	<br class = "clear" />

	<div class = "container">
		<% if flash[:error].present? %>
			<div class = "col-xs-10 col-xs-offset-1 alert alert-danger">
				<%= flash[:error].html_safe %>
			</div>
		<% end %>
		
	</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="col-xs-11 col-xs-offset-1">
	<div class= "row-fluid">
		<div class="col-xs-2 col-sm-4">
			<div class="image_rotation">
				<%= image_tag 'jon.jpeg', :class => 'img-responsive' %>
			</div>
		</div>
		<div class="col-xs-12 col-sm-8">
			<h2 class="my_name">Jonathan Teklu</h2>
				<blockquote>
					<p>
						An extremely talented strategist and program developer within complex environments…effective multilingual international professional…with highly developed cross-cultural interpretation and communication aptitudes…adept at analyzing and synthesizing complex events and data…excellent at attending to detail and recognizing patterns…a proactive and empathic team player…a skilled and effective problem solver  
					</p>	
				</blockquote>
		</div>
	</div>
</div>
<br class="clear" />
<hr />
<div class = "col-xs-10 col-xs-offset-1">
	<h3 class ="title"><u>Comments</u></h3>
	<div class ="comments">
		<h4><%= @page.name %></h4>
		<h4>- <%= @page.message %></h4>
	</div>
</div>

<br class="clear" />
<br />
<hr />

app/views/pages/index.html.erb
<div class="container">
		<br class="clear"/>
		<br />
        	<h1>Welcome! Great to meet you.</h1>
		<br />
			<p>
				<i>I am a Systems Thinker &amp aspiring Web Developer</i>
			</p>
			<br />
        	<p>
				Ruby on Rails Apprentice. Extremely talented strategist. Effective multilingual international professional. Skilled and effective problem solver. Failed, but not a deterred statrtup entrepreneur. Lives for a good challenge. 
			</p>
</div>

<br class = "clear" />
<hr />
<br />

app/views/pages/new.html.erb
<h4>Leave Your Message</h4>
<%= simple_form_for Page.new do |f| %>
	<div class="modal-body">
		<%= f.input :name, :label => "Your name", :placeholder => "John Snow." %>
		<br />
		<%= f.input :message, :lable => "Your comment", :placeholder => "Brothers, winter is coming!" %>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			<%= f.submit 'Post Message', :class => 'btn btn-danger' %>
	</div>
<% end %>